version: "3"

services:
  chirpstack-network-server:
    image: earsnots/chirpstack-network-server-edit:latest
    ports:
      - 80
    volumes:
      - ./configuration/php-apache/sites-available/:/etc/apache2/sites-available/
      - ./configuration/chirpstack-network-server:/etc/chirpstack-network-server
    depends_on:
      - postgresql
      - mosquitto
    restart: "unless-stopped"

  chirpstack-application-server:
    image: chirpstack/chirpstack-application-server:3.17.4
    ports:
      - 8081
    volumes:
      - ./configuration/chirpstack-application-server:/etc/chirpstack-application-server
    depends_on:
      - chirpstack-network-server
    restart: "unless-stopped"

  chirpstack-gateway-bridge:
    image: chirpstack/chirpstack-gateway-bridge:3.13.2
    ports:
      - 1700:1700/udp
    volumes:
      - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
    depends_on: 
      - mosquitto
    restart: "unless-stopped"

  postgresql:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - postgresqldata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: "unless-stopped"
    
  nginx:
    build: ./configuration/nginx/
    ports:
      - 80:80
      - 443:443
    restart: "unless-stopped"

  redis:
    image: redis:5-alpine
    volumes:
      - redisdata:/data
    ports:
      - 6379:6379
    restart: "unless-stopped"

  adminer:
    image: adminer:4.8.1
    restart: "unless-stopped"
    ports:
     - 8080
  
  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - 1883:1883
    restart: "unless-stopped"
    volumes: 
      - ./configuration/eclipse-mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
volumes:
  postgresqldata:
  redisdata:
