FROM php:8.0-apache
RUN cp /etc/apache2/mods-available/rewrite.load /etc/apache2/mods-enabled/
RUN cp /etc/apache2/mods-available/proxy.load /etc/apache2/mods-enabled/
RUN cp /etc/apache2/mods-available/proxy_http.load /etc/apache2/mods-enabled/